### ISSUE TITLE
Missing [Name] in geofences 

### ISSUE THREAD

**Issue by spammer23** [Map-A-Droid/MAD#699] opened 2020-01-21 11:59 UTC
Hi, when creating a geofence in madmin the [name] is missing in the headline.
When it's a quest area it shows in the /quests page as 'unnamed'

Manually inserting the name solves the problem.

**Comment by Expl0dingBanana** [comment] 2020-01-22 11:46
Duplicate of #663

**Closed by Expl0dingBanana** 2020-01-22 11:46 UTC
Labels: Status: Duplicate
