### ISSUE TITLE
Disabling PrioQ is disabled

### ISSUE THREAD

**Issue by Axiangel** [Map-A-Droid/MAD#573] opened 2019-12-02 18:18 UTC
In order to disable PrioQ you need to empty the field delay_after_prio_event in areas complelety. However the new madmin rework will replace a NULL field with 0, making it impossible to disable a PrioQ once enabled. You can prevent your scanners from using it, but valuable resources will be used to calculate it continously.

**Comment by Expl0dingBanana** [comment] 2019-12-03 11:54
What version / commit are you on?  I am not able to reproduce this on the latest master (tried iv, mon, raids)

**Comment by Axiangel** [comment] 2019-12-03 17:54
I'm on lastest master now.
Reproducing would be: Activating PrioQ. Noticing prioQ being generated in MAP/prioQ, removing all prioQ fields (eg. setting delay_after_prio_event to 0), reloading mappings and noticing prioQ routes still being generated in MAP/routes.
It takes a few seconds to get the prioroutes regenerated after restart.

**Comment by Axiangel** [comment] 2019-12-04 13:04
I was able to turn it off eventually.
It's not possible to remove the 0 from delay_after_prio_event directly. "No changes made".
However setting all to a higher number, saving, then deleting and saving would do the trick.

Still a minor bug though. Deleting that 0 should not throw a "No changes made" message.

**Comment by Expl0dingBanana** [comment] 2019-12-05 13:06
This is fixed in #539

**Closed** 2019-12-07 17:59 UTC
Labels: Type: Bug
