### ISSUE TITLE
lastProtoDateTime in trs_status is updating on reboot

### ISSUE THREAD

**Issue by pki0** [Map-A-Droid/MAD#756] opened 2020-02-21 17:29 UTC
Issue 1) 
A device that is connected via RGC but not via PD gets status updates on /status

Issue 2)
Rebooting a device via Devicecontrol gets status updates on /status

To reproduce 1):
- Make PD on your device never connecting to MAD
- Wait for the 20 injection attempts in MAD
- See that lastProtoDateTime in the db got an actual timestamp

To reproduce 2):
- Hit reboot in Devicecontrol

**Comment by sn0opy** [comment] 2020-02-21 19:36
I think you mixed the lastProtoDatetime with the last_data of the /status endpoint. They're different.

But you're right, last_data is being updated once the device reconnects. I was able to reproduce this.

**Comment by pki0** [comment] 2020-02-22 11:51
> I think you mixed the lastProtoDatetime with the last_data of the /status endpoint. They're different.
> 
> But you're right, last_data is being updated once the device reconnects. I was able to reproduce this.

Look at this:

![Bildschirmfoto 2020-02-22 um 12 49 18](https://user-images.githubusercontent.com/21021281/75091830-fba85580-5571-11ea-847c-36791bdba367.png)

I stopped PD at 12:48:00

And I hit Reboot at 12:50:00

![Bildschirmfoto 2020-02-22 um 12 50 16](https://user-images.githubusercontent.com/21021281/75091840-1084e900-5572-11ea-90d2-ebb74d5e3e88.png)

**Comment by sn0opy** [comment] 2020-02-22 12:49
Depending on your settings, PD starts on boot. I tested this and I was not able to reproduce it.

**Comment by pki0** [comment] 2020-03-04 22:06
Any advise/chance to fix this? 
What settings could affect this? What should I change? @sn0opy 

With this bug monitoring is not possible anymore. We cannot figure out if a device is working or not.

**Comment by pki0** [comment] 2020-04-15 14:24
Still happening and waiting for an answer...

Which setting should I change? PD starts on boot but the lastProtoDateTime timestamp is being updated with the **reboot-signal** and not on boot of PD.

I don't know how this can be setting specific. The reboot (via MADmin or from MAD itself) writes a timestamp in the wrong column. 

Maybe the order of my columns are messed up because I applied many DB-patches at once? Can you show me the order it should be, please?

**Comment by Expl0dingBanana** [comment] 2020-04-25 00:05
I just looked at my development instance and I do not have on update current_timestamp() for lastProtoDateTime.

desc trs_status;
+--------------------+------------------+------+-----+---------+-------+
| Field              | Type             | Null | Key | Default | Extra |
+--------------------+------------------+------+-----+---------+-------+
| instance_id        | int(10) unsigned | NO   | MUL | NULL    |       |
| device_id          | int(10) unsigned | NO   | PRI | NULL    |       |
| currentPos         | point            | YES  |     | NULL    |       |
| lastPos            | point            | YES  |     | NULL    |       |
| routePos           | int(11)          | YES  |     | NULL    |       |
| routeMax           | int(11)          | YES  |     | NULL    |       |
| area_id            | int(10) unsigned | YES  | MUL | NULL    |       |
| idle               | tinyint(4)       | YES  |     | 0       |       |
| rebootCounter      | int(11)          | YES  |     | NULL    |       |
| lastProtoDateTime  | timestamp        | YES  |     | NULL    |       |
| lastPogoRestart    | timestamp        | YES  |     | NULL    |       |
| init               | tinyint(1)       | YES  |     | NULL    |       |
| rebootingOption    | tinyint(1)       | YES  |     | NULL    |       |
| restartCounter     | int(11)          | YES  |     | NULL    |       |
| lastPogoReboot     | timestamp        | YES  |     | NULL    |       |
| globalrebootcount  | int(11)          | YES  |     | 0       |       |
| globalrestartcount | int(11)          | YES  |     | 0       |       |
| currentSleepTime   | int(11)          | NO   |     | 0       |       |
+--------------------+------------------+------+-----+---------+-------+

**Comment by Expl0dingBanana** [comment] 2020-04-25 00:10
Whoops thats an old database...  I see the issue in the actual table.  Let me get a fix out for that.

**Comment by Expl0dingBanana** [comment] 2020-04-25 00:32
This should be addressed in #829.  It does change the schema so it is best to backup the table prior to testing the PR.

**Comment by Expl0dingBanana** [comment] 2020-05-19 18:09
Fix has been merged into master.  Please reopen this if you experience any issues

**Closed by Expl0dingBanana** 2020-05-19 18:09 UTC
Labels: Type: Bug
